apis/vshn/v1/dbaas_vshn_postgresql.go, cmd/grpc.go, crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml, pkg/comp-functions/functions/vshn-postgres-func/mailgun_alerting.go, pkg/comp-functions/functions/vshn-postgres-func/mailgun_alerting_test.go, test/transforms/vshn-postgres/alerting/06-GivenNoEmail.yaml, test/transforms/vshn-postgres/alerting/07-GivenEmail.yaml, test/transforms/vshn-postgres/alerting/08-GivenEmptyEmail.yaml
* Adding mailgun alerting for customers
=> Adding mailgun alerting if customer specify email address in claim

cmd/slareport.go, pkg/slareport/prom.go, pkg/slareport/prom_test.go
=> Update target SLA in SLA Reporter

docs/antora-preview.mk, docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/explanations/dev-notes.adoc
Add some dev-notes about comp functions
=> Add some dev-notes about comp functions

docs/modules/ROOT/pages/explanations/comp-functions/vshn-redis.adoc
* Short redis maintenance docs
=> Add redis maintenance docs

pkg/comp-functions/functions/vshnredis/script/recreate.sh
This will add a timeout to the deletion of the sts and if it exceeds that time it will try to patch the finalizers.
There seems to be some weird issue on APPUiO that the first time an sts is deleted with `--cascade=orphan` it will get stuck in the deleting state with a finalizer called `orphan`.
=> Fix an issue with statefulsets stuck in deletion

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/examples/vscode.adoc
* Some vscode launch config samples.
=> Add some vscode samples

pkg/comp-functions/functions/vshn-postgres-func/loadBalancer.go, test/transforms/vshn-postgres/loadbalancer/02-ServiceObserverPresent.yaml
=> fixing objectname to avoid name collisions

pkg/comp-functions/functions/vshn-postgres-func/loadBalancer.go, test/transforms/vshn-postgres/loadbalancer/02-ServiceObserverPresent.yaml
=> renaming object, so it has more meaningful name and it's easier to debug 

pkg/maintenance/postgresql.go
When upgrading stackgres, the mini controller running as a side-car for every postgresql cluster needs to be upgraded first, before we can do any minor upgrades
=> Adjust maintenance procedure for stackgres upgrades

Makefile, cmd/sliexporter.go, config/sliexporter/rbac/role.yaml, go.mod, go.sum, pkg/sliexporter/probes/manager.go, pkg/sliexporter/probes/redis.go, pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller.go, pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller_test.go, pkg/sliexporter/vshnredis_controller/vshnredis_controller.go, pkg/sliexporter/vshnredis_controller/vshnredis_controller_test.go
* Adding Redis prober to sliexporter
=> Redis prober

.github/workflows/docs.yml, docs/modules/ROOT/nav.adoc, docs/package.json
The docs would not publish due to an error. This PR should resolve the issue.
=> Fix docs workflow

Makefile, pkg/controller/webhooks/postgresql.go, pkg/controller/webhooks/postgresql_test.go
=> Add webhook to validate serviceLevel

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/explanations/connectiondetails.adoc
* Detailed documentation how to handle connection details with the composition function framework
=> Add docs about connection details

cmd/grpc.go, pkg/comp-functions/functions/vshnredis/redis_url.go, pkg/comp-functions/functions/vshnredis/redis_url_test.go
* Adding comp-function to generate REDIS_URL as described in docs: https://docs.appcat.ch/references/secrets.html#_redis
=> adding Redis URL

apis/v1/objectstorage_types.go, crds/appcat.vshn.io_objectbuckets.yaml, crds/appcat.vshn.io_xobjectbuckets.yaml, pkg/comp-functions/functions/miniobucket/miniobucket.go
* Add new field to the claim
* Pass it through in the Minio Bucket
=> Add bucket deletion policy for Minio

pkg/controller/webhooks/postgresql.go
* This reflects the product description much better.
=> Adjust wording for HA check

pkg/comp-functions/functions/vshnminio/minio_deploy.go
Seems like the test bucket was not wrapped into an object.
=> Wrap sli bucket into object

README.md, docs/modules/ROOT/pages/explanations/comp-functions/debug.adoc, docs/modules/ROOT/pages/explanations/comp-functions/runtime.adoc, docs/modules/ROOT/pages/explanations/connectiondetails.adoc, docs/modules/ROOT/pages/explanations/dev-notes.adoc
* Update docs to reflect the changes in Crossplane 1.14
=> Adjust docs for crossplane 1.14

pkg/comp-functions/functions/common/namespace-permissions.go, pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go, pkg/comp-functions/functions/vshnmariadb/mariadb_deploy_test.go, test/functions/vshnmariadb/deploy/01_default.yaml
* This PR adds the required RBAC rules in order to be able to access the created service
=> Add Rbac rules for new MariaDB service

apis/vshn/v1/common_types.go, apis/vshn/v1/dbaas_vshn_postgresql.go, pkg/common/utils/plans.go, pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
* This PR implements the handling of nodeSelector based on the end users configuration
=> Add support nodeSelector for MariaDB offering

pkg/comp-functions/functions/common/instance_namespace.go
- The name of the constant was a bit confusing
=> Rename field to a less confusing name

pkg/comp-functions/functions/common/securitycontext.go, pkg/comp-functions/functions/vshnminio/register.go, pkg/comp-functions/functions/vshnminio/securitycontext.go, pkg/comp-functions/functions/vshnminio/utils.go, pkg/comp-functions/runtime/function_mgr.go
This will avoid very long starting times on OpenShift if there are many files in the PVCs.
=> Patch Minio sts with SELinux settings

pkg/comp-functions/functions/common/backup/backup.go, pkg/comp-functions/functions/common/backup/backup_test.go, pkg/comp-functions/functions/common/util.go, pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go, pkg/comp-functions/runtime/function_mgr.go
* This PR will make sure that custom user MariaDB settings are being applied along with the default settings for Galera.
=> Fix custom mariadb settings

docs/modules/ROOT/pages/explanations/eventforwarding.adoc, pkg/comp-functions/runtime/function_mgr.go
* Adds event forwarding for all services under appcat. This applies to services that have their CRs managed by comp functions
=> Event forward in comp function services

apis/vshn/v1/vshn_minio.go, apis/vshn/v1/zz_generated.deepcopy.go, crds/vshn.appcat.vshn.io_vshnminios.yaml, crds/vshn.appcat.vshn.io_xvshnminios.yaml, pkg/comp-functions/functions/vshnminio/register.go
* Adding VSHNMinio user alerting 
=> Adding minio user alerting

apis/vshn/v1/common_types.go, apis/vshn/v1/common_types_test.go, apis/vshn/v1/dbaas_vshn_keycloak.go, apis/vshn/v1/dbaas_vshn_mariadb.go, apis/vshn/v1/dbaas_vshn_postgresql.go, apis/vshn/v1/dbaas_vshn_redis.go, apis/vshn/v1/vshn_minio.go, apis/vshn/v1/vshn_nextcloud.go, pkg/comp-functions/functions/common/maintenance/maintenance.go, pkg/comp-functions/functions/common/maintenance/maintenance_test.go, pkg/comp-functions/functions/common/postgresql.go, pkg/comp-functions/functions/common/schedule.go, pkg/comp-functions/functions/vshnkeycloak/deploy.go, pkg/comp-functions/functions/vshnkeycloak/deploy_test.go, pkg/comp-functions/functions/vshnnextcloud/deploy.go, pkg/comp-functions/functions/vshnnextcloud/deploy_test.go, pkg/comp-functions/functions/vshnpostgres/schedule_test.go
* This PR does refactoring for TimeOfDay field.
* This PR makes sure the database maintenance runs after main service maintenance.
=> Refactor time of day in maintenance

pkg/comp-functions/functions/common/nonsla/alerting.go, pkg/comp-functions/functions/vshnkeycloak/deploy.go
* This PR ensured that keycloak is restarted whenever the end user update its configuration
=> Add keycloak cm hash

package/crossplane.yaml, package/crossplane.yaml.template, package/package.mk
* Using the embeded runtime makes it easier for us, especially when we can't use the github registry directly (eg. pass-through proxy)
=> Ensure we use the embeded runtime in the function package

README.md
* This is just a dummy change to trigger a clean CI release again
=> Small change to test CI again

pkg/comp-functions/functions/vshnpostgres/user_management.go
* Small fix to user credentials
=> fixing bug in connection details

apis/vshn/v1/dbaas_vshn_postgresql.go, crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml, crds/vshn.appcat.vshn.io_vshnnextclouds.yaml, crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml, crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml, crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml, crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
* This PR adds support for PostgreSQL 16
=> Add support for PostgreSQL 16

pkg/comp-functions/functions/vshnnextcloud/deploy.go
It was possible that Nextcloud started without PostgreSQL being ready. This new initcontainer will make sure that PostgreSQL is reachable before attempting to start the main Nextcloud container.
=> Add initcontainer to wait for PostgreSQL

apis/vshn/v1/dbaas_vshn_postgresql.go, crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml, crds/vshn.appcat.vshn.io_vshnmariadbs.yaml, crds/vshn.appcat.vshn.io_vshnnextclouds.yaml, crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml, crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml, crds/vshn.appcat.vshn.io_xvshnmariadbs.yaml, crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml, crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
* Stackgres 1.14 allows Postgres 17 
=> Support Postgres 17

apis/vshn/v1/dbaas_vshn_postgresql.go, crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml, crds/vshn.appcat.vshn.io_vshnnextclouds.yaml, crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml, crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml, crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml, crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml, pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
* Adding new parameter allowing users to disable PgBouncer in our VSHNPostgreSQL
=> Allow to disable PgBouncer in VSHNPostgreSQL

pkg/comp-functions/functions/vshnpostgres/pgqexporter_config.go, pkg/comp-functions/functions/vshnpostgres/register.go, pkg/comp-functions/functions/vshnpostgres/scripts/queries.yml
StackGres' default exporter configuration doesn't play well with large databases.
=> Add new custom pg exporter config

pkg/comp-functions/functions/vshnnextcloud/deploy.go
* Fix nextcloud image registry
=> Fix nextcloud image registry

pkg/comp-functions/functions/vshnforgejo/deploy.go
* Forgejo was rebased with not-so-current commit, therefore it missed one argument in function
=> updating function call updated in other branch

pkg/comp-functions/functions/vshnpostgres/user_management.go, pkg/comp-functions/functions/vshnpostgres/user_management_test.go
=> Fix typo in sslMode for provider-sql

pkg/comp-functions/functions/vshnpostgres/connection_details.go
If another object is referenced via the connectionDetails for a kube object, it can happen that the kube object can't be deleted, if the referenced object is deleted first.
In this specific case, we used to reference the secret that StackGres creates to expose the root password via the connectionDetails of the `cluster` kube object. However that secret is managed by StackGres. So it will be created by StackGres once a sgcluster object is created.
This sgcluster object is managed by the `cluster` kube object, which leads to the race condition.
It can happen that StackGres is faster with removing the secret than provider-kubernetes in remove the `cluster` kube object. When that happens the `cluster` kube object doesn't get deleted, because provider-kubernetes throws observation warnings. …
=> Use separate observer for root password

apis/vshn/v1/dbaas_vshn_keycloak.go, crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml, crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
=> Update CRD validation for Keycloak 26

cmd/maintenance.go, pkg/comp-functions/functions/vshnforgejo/backup.go, pkg/comp-functions/functions/vshnforgejo/deploy.go, pkg/comp-functions/functions/vshnforgejo/maintenance.go, pkg/comp-functions/functions/vshnforgejo/register.go, pkg/maintenance/forgejo.go, pkg/maintenance/helm/helmpatcher.go
* Adds maintenance to `VSHNForgejo`
Related PR in `component-appcat`: https://github.com/vshn/component-appcat/pull/643
=> Forgejo: Add maintenance

pkg/comp-functions/functions/vshnnextcloud/collabora.go
* Fix Collabora regenerating RSA keys on each reconcilation
=> Collabora: Fix perpetual RSA key regeneration

pkg/comp-functions/functions/vshnforgejo/deploy.go
=> Forgejo: Fix ROOT_URL

apis/vshn/v1/dbaas_vshn_keycloak.go, crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml, crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
=> Adjust default version for Keycloak

apis/codey/dbaas_vshn_codey.go, cmd/controller.go, config/controller/cluster-role.yaml, config/controller/webhooks.yaml, pkg/controller/webhooks/codey.go, pkg/scheme.go
* Checks if a to-be-created  `CodeyInstance` will use an unique FQDN, deny its creation otherwise
=> Check Codey FQDN uniqueness

pkg/comp-functions/functions/common/tls.go, pkg/comp-functions/functions/vshnforgejo/deploy.go, pkg/comp-functions/functions/vshnkeycloak/deploy.go, pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go, pkg/comp-functions/functions/vshnnextcloud/deploy.go
=> Make any image configurable

pkg/comp-functions/functions/vshnpostgres/extensions.go, pkg/comp-functions/functions/vshnpostgres/extensions_test.go
* Set the latest version of pg_repack
=> Set latest version of pg_repack extension

apis/vshn/v1/vshn_nextcloud.go, crds/vshn.appcat.vshn.io_vshnnextclouds.yaml, crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml, pkg/comp-functions/functions/vshnnextcloud/collabora.go, pkg/comp-functions/functions/vshnnextcloud/collabora_test.go, pkg/comp-functions/functions/vshnnextcloud/deploy.go, test/functions/vshnnextcloud/01_default.yaml, test/functions/vshnnextcloud/01_no_fqdn.yaml
* Allow configuring the Collabora version in VSHNNextcloud
=> Add Version to CollaboraSpec

hack/diff/compare.sh
This makes the diff renderer compatible with the comp functions. It will chose the latest function available on the target cluster and run the diff against it.
=> Run diff against latest version on the cluster

.cruft.json, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/pr.yml
Enables the new git workflow.
Component PR: https://github.com/vshn/component-appcat/pull/754
=> Enable Gitflow

.cruft.json, .github/workflows/pr.yml
Only trigger release on master
=> Only trigger release on master

apis/vshn/v1/dbaas_vshn_keycloak.go, apis/vshn/v1/dbaas_vshn_postgresql.go, apis/vshn/v1/zz_generated.deepcopy.go, crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml, crds/vshn.appcat.vshn.io_vshnnextclouds.yaml, crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml, crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml, crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml, crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml, pkg/apiserver/vshn/keycloak/get.go, pkg/apiserver/vshn/keycloak/table.go, pkg/comp-functions/functions/common/postgresql.go, pkg/comp-functions/functions/vshnkeycloak/deploy.go, pkg/comp-functions/functions/vshnkeycloak/scripts/copy-kc-creds.sh, pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go, pkg/comp-functions/functions/vshnpostgres/scripts/copy-pg-backup.sh, test/functions/vshn-postgres/base.yaml
* This PR adds support for restoring keycloaks.
=> Add automated restore for Keycloak

cmd/sliexporter.go, pkg/sliexporter/probes/common.go, pkg/sliexporter/probes/http.go, pkg/sliexporter/probes/http_test.go, pkg/sliexporter/probes/maintenance_ctx.go, pkg/sliexporter/probes/manager.go, pkg/sliexporter/probes/manager_test.go, pkg/sliexporter/probes/mariadb.go, pkg/sliexporter/probes/minio.go, pkg/sliexporter/probes/minio_test.go, pkg/sliexporter/probes/postgresql.go, pkg/sliexporter/probes/postgresql_test.go, pkg/sliexporter/probes/redis.go, pkg/sliexporter/sli_reconciler/reconciler.go, pkg/sliexporter/vshnkeycloak_controller/vshnkeycloak_controller.go, pkg/sliexporter/vshnmariadb_controller/vshnmariadb_controller.go, pkg/sliexporter/vshnminio_controller/vshnminio_controller.go, pkg/sliexporter/vshnminio_controller/vshnminio_controller_test.go, pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller.go, pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller_test.go, pkg/sliexporter/vshnredis_controller/vshnredis_controller.go, pkg/sliexporter/vshnredis_controller/vshnredis_controller_test.go
* Extends the Redis SLI prober with custom HA metrics
* Adds alerting rules based on those new metrics
Component PR: https://github.com/vshn/component-appcat/pull/897
=> Redis HA alerting

pkg/comp-functions/functions/vshnpostgres/scripts/queries.yml
* This PR updates the psql queries for stackgres to the latest version.
* This is required to ensure that all queries run as expected.
Component PR: https://github.com/vshn/component-appcat/pull/903
=> Update psql stackgres queries to the latest version

pkg/comp-functions/functions/vshnnextcloud/deploy.go
* Create service account via nextcloud release custom resource
* Create cluster role binding that binds the above service account to a cluster role from component which is linked to an scc
* SCC and cluster role are defined in component.
Component PR: https://github.com/vshn/component-appcat/pull/907
=> Add nextcloud scc

pkg/comp-functions/functions/common/backup/backup.go, pkg/comp-functions/functions/vshnpostgrescnpg/backup.go, pkg/comp-functions/functions/vshnpostgrescnpg/backup_test.go, pkg/comp-functions/functions/vshnpostgrescnpg/deploy.go, pkg/comp-functions/functions/vshnpostgrescnpg/deploy_test.go, test/functions/vshn-postgres/deploy/05_backup_cnpg.yaml, test/functions/vshn-postgres/deploy/05_backup_disabled_cnpg.yaml
* CNPG backup using barman object store
Component PR: https://github.com/vshn/component-appcat/pull/935
=> Feature: CNPG backup 
