vshn/appcat

- apis/appcat/v1/vshn_postgres_backup_types.go
- apiserver/vshn/postgres/table.go
* This PR makes sure that a new column `STORED TIME` is displayed when list/watch operation is issued. 
> Add stored time to table

- config/aggregated-apiserver.yaml
- config/apiserver-envs.yaml
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/references/env-variables.adoc
- main.go
* Adding logic to enable specific features of appcat-apiserver based on env variables
> Add env variables to control modules of api-server

- config/controller/cluster-role.yaml
- controller/postgres/deletion_protection.go
- controller/postgres/deletion_protection_test.go
- controller/postgres/reconciler.go
- controller/postgres/reconciler_test.go
* If the instance namespace is deleted, then the controller will disable the deletion protection on the composite
> Override deletion protection on instance namespace deletion

- pkg/reporting/render.go
- pkg/reporting/render_test.go
- pkg/reporting/template/sla-report.txt
Added a go template that will output an asciidoc ready template for docgen.
> Add SLA report template

- pkg/apiserver/vshn/postgres/vshnpostgresql.go
This prevented the pg backup listing from working properly.
> Fix composite label name

- pkg/comp-functions/functions/vshn-postgres-func/mailgun_alerting.go
- pkg/comp-functions/functions/vshn-postgres-func/mailgun_alerting_test.go
- test/transforms/vshn-postgres/alerting/06-GivenNoEmail.yaml
- test/transforms/vshn-postgres/alerting/07-GivenEmail.yaml
- test/transforms/vshn-postgres/alerting/09-GivenEmailAlertingDisabled.yaml
- test/transforms/vshn-postgres/alerting/10-GivenNoEmailAlertingDisabled.yaml
This PR adds the option to enable and disable the email alerting feature. This is necessary so that we don't accidentally create a Alertmanager config to send email alerts if email alerting isn't enabled at all for the cluster.
See companion PR for component: https://github.com/vshn/component-appcat/pull/169
> Add option to enable and disable email alerting feature for postgresql

- pkg/comp-functions/functions/vshnredis/script/backup.sh
Previously the script didn't actually disable the AOF rewrite prior to taking the backup.
See: https://redis.io/docs/management/persistence/
> Actually disable the AOF rewrite before backup

- apis/appcat/v1/vshn_postgres_backup_types.go
- pkg/apiserver/vshn/postgres/table.go
* After some research it turns out that the _end time_ of a postgres backup is the relevant timestamp that we have to show to the customer. All the data is saved and available up to this timestamp.
> Update postres backup table

- pkg/apiserver/vshn/redis/delete.go
Deletion should not return an error. It looks like the kube-controller calls the deletion function when a namespace is deleted.
> Don't return error on deletion

- apis/stackgres/v1/sgdbops.go
- cmd/maintenance.go
- docs/modules/ROOT/pages/explanations/comp-functions/vshn-postgres.adoc
- pkg/maintenance/postgresql.go
- pkg/maintenance/postgresql_test.go
* This PR adds another step in the maintenance of VSHN Postgres instances. After any update/upgrade is done, the `pg_repack` is performed on all databases.
* This step is part of the cronjob and not of the composition functions.
> Add vshn postgres repack to maintenance

- pkg/comp-functions/functions/vshn-postgres-func/maintenance.go
* The reference secret is wrong for pg after redis maintenance was introduced.
> Fix maintenance secret reference in pg

- pkg/maintenance/postgresql.go
- pkg/maintenance/postgresql_test.go
This commit fixes two separate issue with the PostreSQL maintenance script. Both are related to waiting for the upgrade to complete.
* Fixes a panic in case we receive an event with an SGDbOps without any conditions
* Fixes an issue where the script will run repack prematurely, in case there is an event on a different, completed, SGDbOps in the namespace.
The second point is fairly theoretical, but the second one can be reproduced locally, even though it does not seem to occur in production. Probably a timing issue.
> Fix edge cases in PostgreSQL maintenance

- pkg/sliexporter/probes/manager.go
- pkg/sliexporter/probes/manager_test.go
By adding the organization to the ProberInfo, the same AppCat instance can have two different ProberInfos. This meant we did not properly stop probes as for deletion we did not provide the organization.
This fixes the issue we see that the prober tries to connect to a non existing database.
> Use unique key to keep track of probers instead of the whole ProberInfo

- pkg/apiserver/vshn/redis/table.go
- pkg/apiserver/vshn/redis/table_test.go
There was a display issue caused by the classic Go iteration bug. We attached the same object to each row. This meant if kubectl tired to display additional columns (such as the namespace when listing all redis backups over all namespaces) it showed the same data of the last object for every row.
> Fix display issue for Redis Backups

- pkg/comp-functions/functions/vshn-postgres-func/loadBalancer.go
- pkg/comp-functions/functions/vshn-postgres-func/loadBalancer_test.go
- test/transforms/vshn-postgres/loadbalancer/01-LoadBalancerSet.yaml
- test/transforms/vshn-postgres/loadbalancer/02-ServiceObserverPresent.yaml
* Removing code that updated underlying Stackgres Operator
* Adding v1.Service to allow:
** proper ExternalIP assignment 
** proper port-forward when network set to default or ClusterIP
> Adjusting code to cooperate with Cilium

- go.sum
- pkg/comp-functions/functions/vshn-postgres-func/url.go
* Change NewFatal to NewWarning in Url.go to fix composite function on very slow clusters
> fixing url.go function

- README.md
- apis/vshn/v1/common_types.go
- apis/vshn/v1/dbaas_vshn_postgresql.go
- cmd/grpc.go
- crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
- pkg/sliexporter/probes/manager.go
- pkg/sliexporter/probes/postgresql.go
- pkg/sliexporter/probes/postgresql_test.go
- pkg/sliexporter/vshnpostgresql_controller.go
- pkg/sliexporter/vshnpostgresql_controller_test.go
This PR adds `sla` label to the SLI Prober so that it can be used later on by alerts and ultimately arrive in OpsGenie if necessary
> Add service level guaranteed availability

- pkg/slareport/prom.go
- pkg/slareport/prom_test.go
* This PR will add service constraints to the SLA reporter. This will prevent for newly added services in AppCat to be considered too early for SLA reports. 
> Add service constraints to SLA reporter

- pkg/maintenance/redis.go
Previously it checked against the offial Redis image. Which may be further ahead than Bitnami, causing issues.
> Use Bitnami Redis image to check for newer tags

- pkg/comp-functions/functions/vshnminio/minio_deploy.go
The Minio helm chart has some funky logic that changes the fullname variable depending on wheter it contains the string `minio` or not.
This commit will simply set the fullname to the composite name.
Ref:
https://github.com/minio/minio/blob/22ee67813618351ca8a983eee65f6460af7d9afe/helm/minio/templates/_helpers.tpl#L19C22-L19C26
> Override the Minio fullname

- docs/modules/ROOT/pages/explanations/webhooks.adoc
- pkg/common/quotas/quotas.go
- pkg/common/quotas/quotas_test.go
- pkg/common/utils/resources.go
- pkg/common/utils/sidecars.go
- pkg/common/utils/sidecars_test.go
- pkg/comp-functions/functions/common/namespace-quotas.go
- pkg/controller/webhooks/postgresql.go
- pkg/controller/webhooks/postgresql_test.go
- pkg/controller/webhooks/redis.go
- test/transforms/common/quotas/01_default.yaml
* The resources of the sidecars are not taken into account when calculating the quota for the instance namespace. This results in too low quotas for the instance namespace when deploying multiple instances of a PostgreSQL instance, as the namespace doesn't have high enough quota defined.
* This PR addresses this issue, by taking the resources of the sidecars into account when calculating the required quotas for the instance namespace.
> Fix resource calculation by taking sidecars into account

- cmd/slareport.go
- pkg/slareport/prom.go
- pkg/slareport/prom_test.go
- pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller.go
- pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller_test.go
- pkg/sliexporter/vshnredis_controller/vshnredis_controller.go
- pkg/sliexporter/vshnredis_controller/vshnredis_controller_test.go
* Add support for redis sla reports
* Fix wrong service key for Redis and PostgreSQL
> Add redis sla reports and fix wrong service key for redis and postgresql

- pkg/comp-functions/functions/vshnminio/minio_deploy.go
- pkg/comp-functions/functions/vshnminio/minio_deploy_test.go
* Add serviceMonitor for minio to scrape minio metrics
> Add serviceMonitor for minio to scrape minio relevant metrics

- apis/vshn/v1/dbaas_vshn_redis.go
- crds/vshn.appcat.vshn.io_vshnredis.yaml
- pkg/sliexporter/probes/redis.go
- pkg/sliexporter/vshnredis_controller/vshnredis_controller.go
- pkg/sliexporter/vshnredis_controller/vshnredis_controller_test.go
* adding necessary logic to make redis alerting possible
* it's semi-prepared for introduction of HA setup of Redis
> Adding Redis alerting 

- go.mod
- go.sum
There's a high risk [vulnerability](https://github.com/advisories/GHSA-m425-mq94-257g) in our current grpc dependency library.
> Update GRPC dependency

- pkg/comp-functions/functions/vshnminio/minio_deploy.go
- pkg/comp-functions/functions/vshnminio/minio_deploy_test.go
* MinIO scrapes metrics from four different endpoints depending on what the metrics are (cluster, node, bucket, resource)
* We want to scrape all of them to ensure we can effectively monitor the instances as well as the buckets
> Add additional scrape configs for getting minio relevant metrics

- pkg/sliexporter/probes/manager.go
- pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller.go
- pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller_test.go
- pkg/sliexporter/vshnredis_controller/vshnredis_controller.go
- pkg/sliexporter/vshnredis_controller/vshnredis_controller_test.go
The SLI prober fails to stop the prober for an instance in a namespace that was deleted. This leads to a non ending request errors from the prober due to the fact that the namespace is not retrieved anymore from the request itself once it's marked as deleted. The solution is to get the namespace from the XRD labels in case the request is missing it.
> Fix prober when namespace claim is deleted

- package/package.mk
- pkg/comp-functions/functions/common/namespace-quotas.go
This fixes a bug where the quota namespace was not found. It also fixes a bug that would override the namespace with a wrong name.
There's also now an additional check to see if the name of the namespace is empty or not. This helps mitigating wrong patches from the PnT function.
Also found a bug with the release action, goreleaser was failing due to a dirty repository.
> Fix quota namespace not found

- pkg/controller/postgres/deletion_protection.go
- pkg/controller/postgres/deletion_protection_test.go
The controller now checks if there are more than 1 appcat finalizers on the composite and remove all except one if it's the case.
> Remove any excess finalizers

- pkg/controller/events/event_forwarder.go
Some events don't set the `kind` or `apiVersion` of the involvedObject
and some events don't have a proper name.
In all those cases, we don't care about those events and don't process
them.
>  Don't handle events we don't care about 

- pkg/sliexporter/vshnminio_controller/vshnminio_controller.go
- pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller.go
- pkg/sliexporter/vshnredis_controller/vshnredis_controller.go
This fixes a nilpointer when a new instance is deployed. The `Spec.WriteConnectionSecretToReference` is not populated on the first reconcile.
> Fix nilpointer panic when provisioning an instance

- pkg/comp-functions/functions/vshnpostgres/delay_cluster.go
- pkg/comp-functions/functions/vshnpostgres/delay_cluster_test.go
- pkg/comp-functions/functions/vshnpostgres/register.go
- pkg/comp-functions/runtime/function_mgr.go
- test/functions/vshn-postgres/delay_cluster/01_GivenAllDependencies.yaml
- test/functions/vshn-postgres/delay_cluster/01_GivenNoDependency.yaml
This change will delay the creation of the cluster object in such a way that its dependencies need to be deployed first.
This will avoid some reconcile loops in provider-kubernetes, as it will go into a feedback loop and only try to deploy a failed object, while not reconciling the others.
> Delay creation of the cluster object

- pkg/comp-functions/functions/common/instance_namespace.go
- pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
- pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
- pkg/comp-functions/functions/vshnredis/redis_deploy.go
This label is needed for the new Odoo 16 billing. The Prometheus rules that aggregate the necessary metrics need it to expose the name of the claim, which will in turn then be added to the invoice.
> Add claim-name label

- apis/vshn/v1/common_types.go
- apis/vshn/v1/dbaas_vshn_mariadb.go
- apis/vshn/v1/dbaas_vshn_redis.go
- pkg/comp-functions/functions/common/backup/backup.go
- pkg/comp-functions/functions/common/backup/backup_test.go
- pkg/comp-functions/functions/common/interfaces.go
- pkg/comp-functions/functions/common/password.go
- pkg/comp-functions/functions/common/release.go
- pkg/comp-functions/functions/vshnmariadb/backup.go
- pkg/comp-functions/functions/vshnmariadb/backup_test.go
- pkg/comp-functions/functions/vshnmariadb/register.go
- pkg/comp-functions/functions/vshnmariadb/script/backup.sh
- pkg/comp-functions/functions/vshnredis/backup.go
- pkg/comp-functions/functions/vshnredis/backup_test.go
- pkg/comp-functions/functions/vshnredis/pvcresize.go
- pkg/comp-functions/functions/vshnredis/release.go
- test/functions/vshnmariadb/deploy/01_default.yaml
* The backup is done via K8up and MariaBackup. The backup command is added via annotation to the pods. MariaBackup streams the backup to stdout, where K8up picks it up.
* Generalized a lot of logic which injects the annotations and scripts into any given helm values.
> Add MariaDB Backups

- pkg/comp-functions/functions/common/instance_namespace.go
- pkg/comp-functions/functions/common/namespace-quotas.go
- pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
The quota handling still assumes that the org label is patched onto the composite, but that isn't true anymore. Also the organization creation is handled in the `BootstrapInstanceNs()` function. This generates an racecondition between those two functions.
Additionally:
* Don't return fatal in the quota function, this can lead to deadlocks
* Cleaned up some dropped errors
> Don't handle the organization label in quotas

- pkg/comp-functions/functions/common/maintenance/maintenance_test.go
- pkg/comp-functions/functions/vshnpostgres/maintenance.go
- test/functions/vshn-postgres/loadbalancer/02-ServiceObserverPresent.yaml
* This is BREAKING change and requires Stackgres version >= 1.6
* Stackgres changed secret name, so I'm adjusting it
> Adjust stackgres rest-api secret name for stackgres 1.7 upgrade

- pkg/sliexporter/vshnredis_controller/vshnredis_controller.go
- pkg/sliexporter/vshnredis_controller/vshnredis_controller_test.go
* We need to set up TLSConfig only when we're going to use that, otherwise it should remain nil field in our Redis Client Opts. If it's set to even completely empty `&tls.Config{}` it fails to probe non-tls Redises
> Redis prober handles TLS correctly

- crds/stackgres.io_sgpoolingconfigs.yaml
- pkg/controller/webhooks/postgresql.go
- pkg/controller/webhooks/redis.go
* Adding logic to catch too long Redis and PostgreSQL names early
* We add various postfixes to resource name and our limitation is https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names for cronjob resources 
* if we allow resource creation then VSHNRedis is created but underlying objects not, therefore customer would wait indefinitely for database to come up
> block too long db names early

- apis/vshn/v1/dbaas_vshn_keycloak.go
- cmd/maintenance.go
- crds/stackgres.io_sgpoolingconfigs.yaml
- crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
- crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
- pkg/comp-functions/functions/common/maintenance/maintenance.go
- pkg/comp-functions/functions/vshnkeycloak/deploy.go
- pkg/comp-functions/functions/vshnkeycloak/deploy_test.go
- pkg/comp-functions/functions/vshnkeycloak/maintenance.go
- pkg/comp-functions/functions/vshnkeycloak/register.go
- pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
- pkg/comp-functions/functions/vshnredis/release.go
- pkg/maintenance/auth/http.go
- pkg/maintenance/helm/helmpatcher.go
- pkg/maintenance/helm/helmpatcher_test.go
- pkg/maintenance/keycloak.go
- pkg/maintenance/mariadb.go
- pkg/maintenance/minio.go
- pkg/maintenance/minio_test.go
- pkg/maintenance/redis.go
- pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller.go
- pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller_test.go
This commit adds automatic maintenance for Keycloak.
The automatic maintenance now supports private registries. It also now     supports any other registry apart from docker hub.
We've been using the docker hub's rich API until now. But that is exclusive to docker hub. Normal v2 registries have another API. The maintenance now supports that API as well and will automatically fall back to it, if the URL isn't from `https://hub.docker.com`.
> Add automatic maintenance to Keycloak

- pkg/common/quotas/quotas.go
- pkg/common/utils/resources.go
APPUiO's definition of a terminating pod is `.spec.activeDeadlineSeconds >= 0`. It also enforces a `.spec.activeDeadlineSeconds` for all jobs. So essentially all jobs are measured against the terminating quota.
The pgrepack job from StackGres has a hardcoded resource request for CPUs of 1000m which is higher than the default 500m quota for terminating pods. This causes the pgrepack jobs to be stuck because the pods can't be scheduled.
With this commit we set the initial quota for terminating pods to 1000m.
> Adjust terminating quotas for our jobs

- apis/vshn/v1/dbaas_vshn_keycloak.go
- crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
- crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
- pkg/comp-functions/functions/common/maintenance/maintenance.go
- pkg/comp-functions/functions/vshnkeycloak/deploy.go
- pkg/maintenance/keycloak.go
This commit adds an admin account which is intended to be exposed to the user. This enables the user to change the password of the admin user without breaking the internal scripts of the image.
However, there are no safeguards available to prevent the user from changing the password of the internal admin as well.
> Add external admin account

- docs/modules/ROOT/assets/images/disable-billing-flow.drawio.svg
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/explanations/disable-billing.adoc
- pkg/comp-functions/functions/common/instance_namespace.go
- pkg/comp-functions/functions/vshnkeycloak/deploy.go
- pkg/comp-functions/functions/vshnkeycloak/deploy_test.go
- test/functions/vshn-postgres/empty.yaml
- test/functions/vshnkeycloak/01_default.yaml
- test/functions/vshnmariadb/deploy/01_default.yaml
With this commit it's possible to disable the billing for selected services.
It works by deploying a separate config map containing this information in the `appcat-control` namespace. This config map is then read by the service composition function and removes the billing accordingly.
For more detailed information please have a look at the docs in the commit.
> Ability to disable billing for selected services

- pkg/comp-functions/functions/vshnpostgres/extensions.go
For some reason as of 7.3.2024 the installation of the pg_repack extension doesn't work anymore without providing a version string as well.
> Fix pg_repack extension not installing correcltly

- pkg/comp-functions/functions/common/instance_namespace.go
- pkg/comp-functions/functions/vshnpostgres/extensions_test.go
* There was a race condition which could re-create the instance namespace during the upgrade of the appcat function
* Also fixed the tests that broke during a hotfix deployment yesterday
> Mitigate namespace deletion race-condition

- pkg/comp-functions/functions/vshnkeycloak/deploy.go
* The helm chart sets some securityContext by default, this PR removes that
> Fix Keycloak securityContext for OpenShift

- apis/vshn/v1/vshn_minio.go
- crds/appcat.vshn.io_objectbuckets.yaml
- crds/appcat.vshn.io_xobjectbuckets.yaml
- crds/exoscale.appcat.vshn.io_exoscalekafkas.yaml
- crds/exoscale.appcat.vshn.io_exoscalemysqls.yaml
- crds/exoscale.appcat.vshn.io_exoscaleopensearches.yaml
- crds/exoscale.appcat.vshn.io_exoscalepostgresqls.yaml
- crds/exoscale.appcat.vshn.io_exoscaleredis.yaml
- crds/helm.crossplane.io_releases.yaml
- crds/minio.crossplane.io_buckets.yaml
- crds/minio.crossplane.io_policies.yaml
- crds/minio.crossplane.io_users.yaml
- crds/stackgres.io_sgclusters.yaml
- crds/stackgres.io_sgdbops.yaml
- crds/stackgres.io_sgpoolingconfigs.yaml
- crds/stackgres.io_sgpostgresconfigs.yaml
- crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
- crds/vshn.appcat.vshn.io_vshnmariadbs.yaml
- crds/vshn.appcat.vshn.io_vshnminios.yaml
- crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
- crds/vshn.appcat.vshn.io_vshnredis.yaml
- crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
- crds/vshn.appcat.vshn.io_xvshnmariadbs.yaml
- crds/vshn.appcat.vshn.io_xvshnminios.yaml
- crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
- crds/vshn.appcat.vshn.io_xvshnredis.yaml
Without the `inline` json tag, the field will be nested a level deeper in the object. This will lead to empty fields during runtime, as the marshaller can't correctly unmarshal the K8s objects.
> Fix wrong JSON tag

- pkg/comp-functions/functions/vshnpostgres/files/queries.yml
- pkg/comp-functions/functions/vshnpostgres/pgqexporter_config.go
- pkg/comp-functions/functions/vshnpostgres/pgqexporter_workaround.go
- pkg/comp-functions/functions/vshnpostgres/register.go
Stackgres uses very outdated postgresql-exporter which has by default enabled tons of telemetry scraping. Such scrapes tends to OOM for bigger databases, with this PR I was able to limit memory usage for database (100 tables each having 100 columns and each column having 1000 rows) to around ~11-12 MB of `container_memory_usage_bytes{}` and ~10-11 MB of rss. It SHOULD be backward compatible with our Grafana dashboards. 
Fun fact:
queries were reduced by ~800 lines :zany_face: 
> injecting minimalistic postgresql-exporter configuration file

- pkg/sliexporter/vshnkeycloak_controller/vshnkeycloak_controller.go
The composite is cluster scoped, so it does not contain a namespace. Instead it needs to be read from the labels.
> Get namespace via claimnamespace label

- apis/vshn/v1/dbaas_vshn_keycloak.go
- crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
- crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
- pkg/comp-functions/functions/vshnkeycloak/deploy.go
* Keycloak metrics are now enabled and scraped
* Keycloak 24 is available alongside with Keycloak 23 
* Keycloak 24 has image with automatically configured and enabled metrics
> Keycloak metrics 

- pkg/comp-functions/functions/vshnpostgres/connection_details.go
- pkg/comp-functions/functions/vshnpostgres/loadBalancer.go
* The loadbalancer logic still relied on the old connection detail secret, that has been removed 
* This prevented the service to ever get synced/ready, as it was erroring while looking for the secret
> Fix loadbalancer issues

- pkg/maintenance/helm/helmpatcher.go
There was a typo in the api detection which lead to chosing the wrong API, thus breaking the maintenance.
> Fix typo preventing the correct api being called

- config/controller/webhooks.yaml
- pkg/controller/webhooks/postgresql.go
* There's a case where stackgres produces even longer suffixes
> Reduce max length even further

- pkg/comp-functions/functions/vshnpostgres/loadBalancer.go
- pkg/comp-functions/functions/vshnpostgres/loadBalancer_test.go
- pkg/comp-functions/functions/vshnpostgres/register.go
* Some APPUiO managed instances need specific labels on the `service` objects to work properly
* This change allows passing these annotations via the composition inputs
* Also fix an issue where the `primary-service` is not deployed if loadbalancer is disabled. It's still necessary for port-forwarding
> Inject loadbalancer specific annotations

- pkg/sliexporter/probes/manager.go
Currently, the logs don't indicate at all that the probes are failing if there are timeouts. We only export that information.
This makes it hard to find these, as the Sloth metrics don't indicate the type of errors. We have to look at the raw SLI metrics to find out that there are timeouts.
> Also log if the probe has a timeout

- apis/vshn/v1/common_types.go
- apis/vshn/v1/dbaas_vshn_keycloak.go
- apis/vshn/v1/dbaas_vshn_mariadb.go
- apis/vshn/v1/dbaas_vshn_postgresql.go
- apis/vshn/v1/dbaas_vshn_redis.go
- apis/vshn/v1/vshn_minio.go
- crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
- crds/vshn.appcat.vshn.io_vshnmariadbs.yaml
- crds/vshn.appcat.vshn.io_vshnminios.yaml
- crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
- crds/vshn.appcat.vshn.io_vshnredis.yaml
- crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
- crds/vshn.appcat.vshn.io_xvshnmariadbs.yaml
- crds/vshn.appcat.vshn.io_xvshnminios.yaml
- crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
- crds/vshn.appcat.vshn.io_xvshnredis.yaml
- hack/bootstrap/template.go
- pkg/comp-functions/functions/common/instance_namespace.go
- pkg/comp-functions/functions/common/interfaces.go
- pkg/comp-functions/functions/common/netpol.go
- pkg/comp-functions/functions/vshnkeycloak/deploy.go
- pkg/comp-functions/functions/vshnminio/minio_deploy.go
* This PR exposes another field `allowAllNamespaces` which overrides the values in `allowNamespaces`.
* Tested in lab
> Add allowAllNamespaces field

- apis/vshn/v1/dbaas_vshn_postgresql.go
- crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
- crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
- crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
- crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
- pkg/comp-functions/functions/common/maintenance/maintenance.go
- pkg/comp-functions/functions/vshnpostgres/maintenance.go
- pkg/controller/webhooks/postgresql.go
- pkg/controller/webhooks/postgresql_test.go
- pkg/maintenance/postgresql.go
- pkg/maintenance/postgresql_test.go
* This PR gives possibility to set vacuum and/or repack to be run during maintenance
> Support for both Vacuum and Repack

- pkg/maintenance/helm/helmpatcher.go
- pkg/maintenance/helm/helmpatcher_test.go
This commit fixes two things:
* If the slice with tags is empty, it will exit with an error. This should help detect issues with wrong urls.
* If current tag is the latest one, it will return the exact same tag. Not a semver representation of it.
The second point avoids issues if there is a tag v1.0 of an image, but no tag v1.0.0. As the semver representation will always contain three parts for the version.
> Fix setting broken tags

- pkg/comp-functions/functions/vshnpostgres/extensions.go
- pkg/comp-functions/functions/vshnpostgres/extensions_test.go
- test/functions/vshn-postgres/extensions/01-GivenAlreadyEnabled.yaml
- test/functions/vshn-postgres/extensions/01-GivenFreshConfig.yaml
This commit fixes a bug where we overwrote observed pg settings to the desired pg settings.
This caused custom settings specified in the claim to never reach the K8s API in the first place. So the observed state always contained the default settings that StackGres injects into the object.
> Don't override pgSettings with observed values

- pkg/comp-functions/functions/common/nonsla/alerting.go
- pkg/comp-functions/functions/common/nonsla/alerting_test.go
- pkg/comp-functions/functions/vshnpostgres/alerts.go
- pkg/comp-functions/functions/vshnpostgres/register.go
* Some time ago the alert got lost between migration from PnT to comp function
* Changed the naming of the generic alerts, so they actually have generic names
> Add max connection alert

- apis/minio/v1/bucket_types.go
- apis/minio/v1/policy_types.go
- apis/minio/v1/user_types.go
- apis/minio/v1/zz_generated.deepcopy.go
- config/controller/cluster-role.yaml
- pkg/controller/postgres/reconciler.go
Some combinations of OpenShift and client library can cause this issue. Either OpenShift requires more stricter RBAC or the client library do changes they didn't before. Either way: https://access.redhat.com/solutions/5372461
> Fix controller not having enough RBAC

- pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
The Restore object will never be nil.
We need to check for the fields in the Restore object directly.
> Fix bug in copyjob

- pkg/comp-functions/runtime/function_mgr.go
- pkg/comp-functions/runtime/naming.go
- pkg/comp-functions/runtime/naming_test.go
All managed resources and kube objects will now be automatically escaped. K8s naming allows different naming schemes for different objects, the current logic should cover most of them. Unfortunately there's no official docs about which objects support which naming.
> Escape Object names before applying

- pkg/comp-functions/functions/common/password.go
- pkg/comp-functions/runtime/function_mgr.go
- pkg/comp-functions/runtime/naming.go
- pkg/comp-functions/runtime/naming_test.go
I think I dropped this escape call at one point when doing a rebase...
> Escape the names of generated secrets

- pkg/comp-functions/functions/common/resources.go
- pkg/comp-functions/functions/common/resources_test.go
- pkg/comp-functions/functions/vshnkeycloak/deploy.go
- pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
- pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
- test/functions/plans.yaml
The resource calculation between the used plan and the overridden values in the claim for the respective resources contained wrong calculations.
We refactored the whole calculations sections to get correct calculations while keeping the code as readable as possible.
> Refactor and fix Resource calculations

- pkg/comp-functions/functions/vshnnextcloud/deploy.go
- pkg/comp-functions/functions/vshnnextcloud/deploy_test.go
- test/functions/vshnnextcloud/01_default.yaml
- test/functions/vshnnextcloud/02_no_pg.yaml
* This PR fixes a bug, where the `useExternalPostgreSQL` parameter operates exactly the wrong way. Instead of deploying a PostgreSQL instance when this is enabled, it will deploy one when this parameter is disabled.
* Added tests to catch this issue
> Fix wrong usage of `useExternalPostgreSQL` parameter and add better tests

- apis/vshn/v1/vshn_nextcloud.go
- crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
- crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
* This PR fixes a small bug in the kubebuilder instructions to set the correct default value for the `UseExternalPostgreSQL` parameter
> Fix wrong comment for kubebuilder

- pkg/comp-functions/functions/vshnminio/minio_deploy.go
- pkg/comp-functions/functions/vshnminio/minio_deploy_test.go
- pkg/comp-functions/functions/vshnminio/providerconfig.go
- test/functions/vshnminio/deploy/01_default.yaml
This PR refactors the composition functions to use the generic service approach for MinIO in our component.
Furthermore, we refactor the bootstrapping of the namespace to utilize the availablenamespace bootstrapping function.
> Refactor Minio to use generic service and generic ns bootstrap function

- apis/vshn/v1/common_types.go
- apis/vshn/v1/vshn_nextcloud.go
- crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
- crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
- crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
- crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
- crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
- crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
The FQDN needs to be always set, otherwise the lifeness and readiness probes will fail. Furthermore it doesn't make sense to run a nextcloud without a defined FQDN
- [] Update tests.
> Set the FQDN for nextcloud as a required field

- pkg/comp-functions/functions/common/instance_namespace.go
* The servicename is currently hardcorded in the composition function.
* This PR fixes this issue and sets the correct label for the service type
> Fix hardcoded servicename

- pkg/comp-functions/functions/vshnpostgres/connection_details.go
- test/functions/vshn-postgres/secrets/02_input_function-io.yaml
There is currently a bug in the AddConnectionDetails function that takes the SGcluster from the `observed` rather then the `desired` state. Since this function is run *after* the `DeployPostgreSQL` function and takes the cluster configuration from the `observed` state and at the end writes it to the `desired` state, it will effectively override every change done to the `SGCluster` object in the `DeployPostgreSQL` function.
The function should rather get the `SGCluster` object from the desired stage to avoid this issue.
> Fix a bug, where you can't edit an existing VSHNPostgreSQL instance

- pkg/comp-functions/functions/vshnnextcloud/deploy.go
If the claim-name contains `nextcloud` it will not append `nextcloud` to the `fullName` variable in the helm chart.
However if the claim-name doesn't contain `nextcloud`, then the `fullName` will get a `-nextcloud` appendix, resulting in broken service names.
> Fix connection detail name

- pkg/comp-functions/functions/common/backup/backup.go
- pkg/comp-functions/functions/common/postgresql.go
- pkg/comp-functions/functions/vshnmariadb/backup.go
- pkg/comp-functions/functions/vshnnextcloud/backup.go
- pkg/comp-functions/functions/vshnnextcloud/deploy.go
- pkg/comp-functions/functions/vshnnextcloud/deploy_test.go
- pkg/comp-functions/functions/vshnnextcloud/files/backup.sh
- pkg/comp-functions/functions/vshnnextcloud/maintenance.go
- pkg/comp-functions/functions/vshnnextcloud/register.go
This adds backups to nextcloud. It sets the Nextcloud maintenance mode while doing the backup. The whole /var/www folder will be saved. It also ensures that the database backup is triggered at the same time as well to ensure that both backups are as close together as possible.
> Add backups for nextcloud

- pkg/sliexporter/vshnkeycloak_controller/vshnkeycloak_controller.go
* With Keycloak 25, the health enpdoint changed. We therefore also need to adjust our SLI prober accordingly
> Fix wrong probe path for keycloak for the sli exporter

- apis/exoscale/v1/dbaas_exoscale_postgresql.go
- crds/exoscale.appcat.vshn.io_exoscalepostgresqls.yaml
* This PR adds support for PostgreSQL 15 and 16 on Exoscale.
> Add support for PostgreSQL 15 and 16 on Exoscale

- apis/stackgres/v1/sgcluster.go
- pkg/comp-functions/functions/vshnpostgres/restart.go
* This PR makes sure that whenever the Stackgres Operator is being updated, the postgres clusters will be upgraded only during the maintenance window and not right away.
> Fix operator upgrade restart instance

- apis/vshn/v1/dbaas_vshn_postgresql.go
Our PDB Selector label for vSHNPOstgreSQL accidently matched also backups. This commit fixes it and takes unique label from PostgreSQL pods.
Test case:
- create new VSHNPostgreSQL (3 instances)
- run maintenance
- run backup
- run `k get pod -l stackgres.io/cluster="true"` in instance_namespace
- result - only cluster pods are selected
> fixing PDB selector label

- .github/workflows/diff.yml
- .gitignore
- Makefile
- hack/diff/compare.sh
- hack/diff/function.yaml.tmpl
- main.go
- pkg/maintenance/postgresql_test.go
`make  render-diff` will run a script, that connects to the current cluster in `KUBECONFIG` and runs a diff against the current AppCat branch.
It leverages Crossplane's crank utility to render the result of a single function reconcile. It then uses `dyff`, a YAML and K8s aware diff tool, to actually show the diff itself.
Limitations: it can currently only generate a single reconcile run against the current state. If a function needs multiple reconciles to change the desired state, it won't show up in the diff.
Also, it will only work against a cluster that has at least this version of the AppCat function installed. Otherwise crank won't be able to render it correctly.
> Add script to generate diffs between a cluster and the local branch

- pkg/comp-functions/functions/vshnkeycloak/deploy.go
- pkg/comp-functions/functions/vshnnextcloud/deploy.go
- pkg/comp-functions/functions/vshnpostgres/encrypted_pvc.go
- pkg/comp-functions/functions/vshnpostgres/encrypted_pvc_test.go
- pkg/comp-functions/runtime/function_mgr.go
- test/functions/vshn-postgres/enc_pvc/03-GivenEncryptionParams.yaml
- test/functions/vshn-postgres/enc_pvc/03-GivenEncryptionParamsExistingSecret.yaml
There was a dependency loop that prevented the creation of VSHNPostgreSQL instances that use encrypted PVCs:
* The SGCluster object can't be created before the luks secret for the PVC is generated
* The luks secret can't be created without getting the instance count of the cluster object
This has been resolved by relying on the instance count from the composite and also waiting for the luks secrets to be present before attempting to access the sgcluster object to be able to override the storageClass for the PVCs
> Fix dependency issue when using encrypted PVCs for VSHNPostgreSQL

- apis/v1/objectstorage_types.go
- pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
- pkg/comp-functions/functions/vshnpostgres/postgresql_deploy_test.go
- test/functions/vshn-postgres/deploy/01_default.yaml
- test/functions/vshn-postgres/deploy/02_with_pg_config.yaml
- test/functions/vshn-postgres/deploy/03_with_restore.yaml
Fix probably a bug in our ObjectStorage spec
> Improve PostgreSQL ordering, reduce issues

- Makefile
- README.md
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/explanations/providerconfig-management.adoc
- hack/diff/compare.sh
- hack/diff/function.yaml.tmpl
- pkg/comp-functions/functions/common/backup/backup.go
- pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
- pkg/comp-functions/functions/vshnpostgres/user_management.go
- pkg/comp-functions/runtime/function_mgr.go
- pkg/comp-functions/runtime/function_mgr_test.go
* Each claim/composite pair can specific their own providerConfig name
* It will be injected into each managed resource
* The providerConfigs need to be correctly provisioned beforehand
* Not setting the label will result in the current defaults being used
* Usage will no longer be wrapped into Kube Objects to avoid deploying them to service clusters
* Also it's best practices to NOT wrap them, it makes the deprovisioning process a lot smoother
* It's possible to set a label for managed resources that should not get the providerConf from the claim/composite
* Some managed resources have already been labeled, but by all means not all of them. That should be in the scope of another story
as they show up in the …
> Add providerConfig management

- pkg/controller/webhooks/xobjectbuckets.go
* this PR adds logic to delay deletion of xobjectbucket so we're sure billing run at least once
> adding delayed removal of xobjectbucket

- apis/vshn/v1/dbaas_vshn_keycloak.go
- apis/vshn/v1/dbaas_vshn_mariadb.go
- apis/vshn/v1/dbaas_vshn_postgresql.go
- apis/vshn/v1/dbaas_vshn_redis.go
- apis/vshn/v1/non_gen_types.go
- apis/vshn/v1/vshn_minio.go
- apis/vshn/v1/vshn_nextcloud.go
- pkg/comp-functions/functions/common/billing.go
- pkg/comp-functions/functions/common/interfaces.go
- pkg/comp-functions/functions/vshnkeycloak/billing.go
- pkg/comp-functions/functions/vshnkeycloak/register.go
- pkg/comp-functions/functions/vshnmariadb/billing.go
- pkg/comp-functions/functions/vshnmariadb/register.go
- pkg/comp-functions/functions/vshnminio/billing.go
- pkg/comp-functions/functions/vshnminio/register.go
- pkg/comp-functions/functions/vshnnextcloud/billing.go
- pkg/comp-functions/functions/vshnnextcloud/register.go
- pkg/comp-functions/functions/vshnpostgres/billing.go
- pkg/comp-functions/functions/vshnpostgres/register.go
- pkg/comp-functions/functions/vshnredis/billing.go
- pkg/comp-functions/functions/vshnredis/register.go
* Added a label to each of our services to allow easy scrape of billing metrics 
> Add billing to services

- pkg/comp-functions/functions/vshnredis/backup.go
- pkg/comp-functions/functions/vshnredis/script/backup.sh
* This PR fixes a bug, where the backups didn't work if Redis TLS is disabled.
> Fix backups if Redis TLS is disabled

- apis/vshn/v1/dbaas_vshn_keycloak.go
- apis/vshn/v1/dbaas_vshn_mariadb.go
- apis/vshn/v1/dbaas_vshn_postgresql.go
- apis/vshn/v1/dbaas_vshn_redis.go
- apis/vshn/v1/vshn_minio.go
- apis/vshn/v1/vshn_nextcloud.go
- pkg/comp-functions/functions/common/billing.go
- pkg/comp-functions/functions/common/instance_namespace.go
- pkg/comp-functions/functions/common/interfaces.go
- pkg/comp-functions/functions/vshnkeycloak/billing.go
- pkg/comp-functions/functions/vshnmariadb/billing.go
- pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
- pkg/comp-functions/functions/vshnminio/billing.go
- pkg/comp-functions/functions/vshnnextcloud/billing.go
- pkg/comp-functions/functions/vshnpostgres/billing.go
- pkg/comp-functions/functions/vshnredis/billing.go
Currently we are getting data for billing from the workloads (deployments and statefulsets) special label `appcat.io/billing=true`. This approach proved to be ineffective for some services such as VSHNPostgreSQL which is managed by Stackgres. Unfortunately the operator sometimes is managing the pods directly, by passing the workload. In this particular case we end up without the necessary label in the pod definition.
This new approach manages differently the billing architecture. If previously we were having one prometheus rule which would gather unnecessarily difficult specific data, now we have one rule per each instance namespace and it is managed directly by the composition function where we get reliable data from the source.
`bug`, `enhancement`, `documentation`, `change`, …
> Refactor billing

- pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
* Passing through parameter from claim to helm release
FYI: 
- SLI prober works with this change out of the box - tested in kind and lab
> Add possibility to run MariaDB without TLS

- pkg/comp-functions/functions/vshnkeycloak/billing.go
- pkg/comp-functions/functions/vshnkeycloak/register.go
- pkg/comp-functions/functions/vshnmariadb/billing.go
- pkg/comp-functions/functions/vshnmariadb/register.go
- pkg/comp-functions/functions/vshnminio/billing.go
- pkg/comp-functions/functions/vshnminio/register.go
- pkg/comp-functions/functions/vshnnextcloud/billing.go
- pkg/comp-functions/functions/vshnnextcloud/register.go
- pkg/comp-functions/functions/vshnpostgres/billing.go
- pkg/comp-functions/functions/vshnpostgres/extensions.go
- pkg/comp-functions/functions/vshnpostgres/extensions_test.go
- pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
- pkg/comp-functions/functions/vshnpostgres/postgresql_deploy_test.go
- pkg/comp-functions/functions/vshnpostgres/register.go
- pkg/comp-functions/functions/vshnredis/billing.go
- pkg/comp-functions/functions/vshnredis/register.go
* Seems like we are creating a pg-config object for all instances in a cluster. To resolve this issue we change the name in the desired object.
> Fix pg config

- pkg/comp-functions/functions/vshnpostgres/delay_cluster.go
- pkg/comp-functions/functions/vshnpostgres/extensions.go
- pkg/comp-functions/functions/vshnpostgres/extensions_test.go
- test/functions/vshn-postgres/delay_cluster/01_GivenAllDependencies.yaml
- test/functions/vshn-postgres/extensions/01-GivenAlreadyEnabled.yaml
- test/functions/vshn-postgres/extensions/01-GivenFreshConfig.yaml
* Issues with pg-conf kube object not being updated properly
> Fix pg-conf naming issues

- config/controller/webhooks.yaml
- pkg/controller/webhooks/object.go
* If the v1alpha1 version is not available, the webhook will fail. We will therefore remove it here, and manually add it where required
> Remove v1alpha1 for objects from webhook definition

- apis/vshn/v1/dbaas_vshn_mariadb.go
- crds/vshn.appcat.vshn.io_vshnmariadbs.yaml
- crds/vshn.appcat.vshn.io_xvshnmariadbs.yaml
- pkg/comp-functions/functions/common/resources.go
- pkg/comp-functions/functions/common/tls.go
- pkg/comp-functions/functions/vshnkeycloak/deploy.go
- pkg/comp-functions/functions/vshnmariadb/files/proxysql.conf.tmpl
- pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
- pkg/comp-functions/functions/vshnmariadb/mariadb_deploy_test.go
- pkg/comp-functions/functions/vshnmariadb/proxysql.go
- pkg/comp-functions/functions/vshnmariadb/proxysql_test.go
- pkg/comp-functions/functions/vshnmariadb/register.go
- pkg/comp-functions/functions/vshnmariadb/user_management.go
- pkg/comp-functions/runtime/function_mgr.go
- pkg/controller/webhooks/mariadb.go
With this MariaDB can scale to a 3 node Galera cluster.
* Added ProxySQl statefulset
* Updated default version of MariaDB
* Updated Galera helm chart
* Added sensible PDBs to ProxySQL
> Add MariaDB Scaling

- pkg/comp-functions/functions/vshnmariadb/user_management.go
Crossplane resource names are always lower case. If the name doesn't match exactly, then the usage won't be applied properly.
This lead to a race condition when deprovisioning MariaDB with users.
> Fix typo in the usage protecting the instance NS

- pkg/comp-functions/functions/common/nonsla/alerting.go
- pkg/comp-functions/functions/common/nonsla/alerting_test.go
- pkg/comp-functions/functions/common/nonsla/non_sla_prom_rules.go
- pkg/comp-functions/functions/vshnkeycloak/register.go
- pkg/comp-functions/functions/vshnmariadb/register.go
- pkg/comp-functions/functions/vshnminio/register.go
- pkg/comp-functions/functions/vshnpostgres/alerts.go
- pkg/comp-functions/functions/vshnpostgres/register.go
- pkg/comp-functions/functions/vshnredis/register.go
The current user-workload alerts will not properly work with the cluster workload monitoring, because:
* A specific `"syn": "true"` label is missing
* They don't filter for the namespace. So each alert would trigger for each instance that is running.
The second part needed a bit more involved refactoring, as we have to pass the specific namespace for each instance and can't just match in a generic manner.
> Re-write alerts so they work with cluster monitoring

- cmd/controller.go
- pkg/comp-functions/functions/common/instance_namespace.go
- pkg/comp-functions/functions/vshnkeycloak/deploy.go
- pkg/comp-functions/functions/vshnminio/minio_deploy.go
- pkg/comp-functions/functions/vshnpostgres/objectbucket.go
- pkg/comp-functions/functions/vshnredis/pvcresize.go
- pkg/comp-functions/functions/vshnredis/pvcresize_test.go
- pkg/comp-functions/functions/vshnredis/release.go
- pkg/comp-functions/runtime/function_mgr.go
- pkg/controller/webhooks/deletionprotection.go
- pkg/controller/webhooks/deletionprotection_test.go
- pkg/controller/webhooks/generic_deletionprotection_handler.go
- pkg/controller/webhooks/keycloak.go
- pkg/controller/webhooks/namespace.go
- pkg/controller/webhooks/object.go
- pkg/controller/webhooks/pvc.go
- pkg/controller/webhooks/release.go
- pkg/controller/webhooks/xobjectbuckets.go
* This PR adds support for connecting the webhook controller to another cluster.
> Implement webhook logic for split control-plane - service cluster setup

- pkg/comp-functions/functions/vshnpostgres/restart.go
Without the annotation Crossplane won't be able to remove the old ops and get stuck in `Synced: false` state.
> Allow rotation of the restart ops

- pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
After an instance has been restored and some of the fields get cleaned the cluster kube object can still have a non-nil `initialData` field containing empty values.
Previously we only checked if the whole field is nil, but we also need to check if the BackupName is empty or not.
> Prevent empty BackupNames from being referenced

- pkg/controller/webhooks/deletionprotection.go
XObjectBuckets and mysql provder-sql objects did not have a valid cpClient specified. This causes nilpointers if any of these should get deleted.
Resulting in errors like these:
```
Error from server (InternalError): Internal error occurred: failed calling webhook "users.mysql.vshn.appcat.vshn.io": failed to call webhook: Post "https://webhook-service.syn-appcat.svc:443/validate-mysql-sql-crossplane-io-v1alpha1-user?timeout=10s": EOF
```
These are Crossplane managed resources and always reside on the control plane.
So they will always have the same clients for local and control plane connections.
If the cpClient isn't specified we default to the other client. This change will make it easier in the future to add managed resources as we don't have to specify both clients seperately (and …
> Use a default client if controlPanel client is nil

- apis/vshn/v1/dbaas_vshn_postgresql.go
- crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
- crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
- crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
- crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
- crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
- crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
* There is a type in the disable pg bouncer parameter.
> Fix disable pg bouncer name parameter

- pkg/comp-functions/functions/common/pdb.go
* Currently whenever the pg instnace is being rescaled the PDB cannot be deleted by crossplane as it is protected by deletion protection.
> Allow deletion of PDBs

- apis/vshn/v1/vshn_nextcloud.go
- apis/vshn/v1/zz_generated.deepcopy.go
- crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
- crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
- pkg/comp-functions/functions/vshnnextcloud/collabora.go
- pkg/comp-functions/functions/vshnnextcloud/collabora_test.go
- pkg/comp-functions/functions/vshnnextcloud/deploy.go
- pkg/comp-functions/functions/vshnnextcloud/deploy_test.go
- pkg/comp-functions/functions/vshnnextcloud/ingress.go
- pkg/controller/webhooks/default_handler_test.go
- pkg/controller/webhooks/nextcloud.go
- pkg/controller/webhooks/nextcloud_test.go
- test/functions/vshnnextcloud/01_no_fqdn.yaml
- test/functions/vshnnextcloud/02_no_pg.yaml
- test/functions/vshnnextcloud/02_withFQDN.yaml
* This PR will change the FQD parameter from a string to an array, so that the end user can specify multiple endpoints.
> Use an array instead of a string for the FQDN parameter

- pkg/comp-functions/functions/common/billing.go
This will not deploy any billing data for instances where the claim resides in the `vshn-test` namespace.
> Don't deploy billing prometheus rule for tests

- apis/vshn/v1/dbaas_vshn_postgresql.go
- crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
* Without this setting some applications might refuse to work with "Server does not support TLS connections"
* caused by .spec.parameters.service.tls = nil
> Hotfix: adding missing tls={} configuration to claim

- apis/vshn/v1/dbaas_vshn_postgresql.go
- crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
*Without this setting some applications might refuse to work with "Server does not support TLS connections"
*caused by .spec.parameters.service.tls = nil
> adding missing reference in vshnpostgresql claim

- apis/vshn/v1/dbaas_vshn_postgresql.go
- crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
* Fixing TLS settings
* For context: there is a difference if we initialize nested map inside some struct and single field. I had to add `properties` entry to generator to make it work.
* Currently our XVSHNPostgreSQL receives new struct inside `spec.parameters.service` and has a form:
```        
repackEnabled: true
serviceLevel: besteffort
++  tls:
++      enabled: true
vacuumEnabled: false
```
* test cases I did:
** new instance
** existing instance during migration from `master` branch
** existing instances with previous fixes and partially applied fields
> add TLS fix

- apis/vshn/v1/vshn_nextcloud.go
- pkg/comp-functions/functions/common/billing.go
- pkg/comp-functions/functions/common/billing_test.go
- pkg/comp-functions/functions/vshnnextcloud/billing.go
- test/functions/common/billing.yaml
* Adds nextcloud office billing
* Adds support for billing service add ons via functional parameters
* Adds tests
> Enable nextcloud office billing

- pkg/comp-functions/functions/vshnpostgres/maintenance.go
- pkg/comp-functions/functions/vshnpostgres/postgresql_deploy_test.go
- test/functions/vshn-postgres/deploy/01_default.yaml
We need to ensure that the SGCluster always contains the "correct" version and that we don't override it with just a major version. The reason is, that Stackgres doesn't allow changing the version number in the `SGCluster` object. Since stackgres changes the version field during a minor upgrade, it won't be possible anymore to "revert" this change to a major version only setting.
> Set the correct version for the SGCluster

- apis/vshn/v1/dbaas_vshn_mariadb.go
- apis/vshn/v1/dbaas_vshn_redis.go
- apis/vshn/v1/vshn_minio.go
- cmd/sliexporter.go
- pkg/apiserver/appcat/appcat.go
- pkg/apiserver/common.go
- pkg/apiserver/vshn/mariadb/backup.go
- pkg/apiserver/vshn/nextcloud/backup.go
- pkg/apiserver/vshn/postgres/backup.go
- pkg/apiserver/vshn/redis/backup.go
- pkg/common/utils/kinds.go
- pkg/comp-functions/functions/common/interfaces.go
- pkg/sliexporter/maintenance_controller/controller.go
- pkg/sliexporter/sli_reconciler/reconciler.go
- pkg/sliexporter/vshnkeycloak_controller/vshnkeycloak_controller.go
- pkg/sliexporter/vshnkeycloak_controller/vshnkeycloak_controller_test.go
- pkg/sliexporter/vshnmariadb_controller/vshnmariadb_controller.go
- pkg/sliexporter/vshnmariadb_controller/vshnmariadb_controller_test.go
- pkg/sliexporter/vshnminio_controller/vshnminio_controller.go
- pkg/sliexporter/vshnminio_controller/vshnminio_controller_test.go
- pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller.go
- pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller_test.go
- pkg/sliexporter/vshnredis_controller/vshnredis_controller.go
- pkg/sliexporter/vshnredis_controller/vshnredis_controller_test.go
This adds support for remote control planes for the SLI exporter. It now
takes an additional `KUBECONFIG` env var to connect to the control plane.
Additionally to determine the state of the maintenance of the service
cluster, it connects to the local service cluster to reconcile on
`UpgradeJob` objects.
Also the SLI-Prober doesn't need any configuration about the services
anymore. It will detect these on startup.
> Add support for remote control plane to SLI exporter

- apis/vshn/v1/dbaas_vshn_postgresql.go
- crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
- crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
- crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
- crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
- crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
- crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
* Our defaults in CRD should reflect what's written to docs.appcat.ch
> correct default in postgresql crds

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/postCreateCommand.sh
- .gitignore
- Makefile
- README.md
* Adds support for devcontainers to streamline the dev ux
> Add support for devcontainers

- pkg/comp-functions/functions/common/billing.go
- pkg/comp-functions/functions/common/instance_namespace.go
This PR will switch the monitoring of the instances from cluster monitoring to user-workload monitoring.
This is required to have alerting and monitoring work for the end users
> Switch instances monitoring from cluster to user-workload monitoring

- pkg/comp-functions/functions/vshnnextcloud/collabora.go
- pkg/comp-functions/functions/vshnnextcloud/deploy.go
Currently, the registry is hardcoded to docker.io. However, we want to be able to use a different registry in some cases (eg. to avoid rate-limiting). Using this parameter allows us to change the registry for the nextcloud image to another registry.
> Add image repository parameter, to be able to override the registry

- pkg/comp-functions/functions/vshnnextcloud/deploy.go
* This PR adds a new sideCar that runs the cron jobs for the nextcloud instance
> Add sidecar for nextcloud cron jobs

- config/sliexporter/default/manager_auth_proxy_patch.yaml
`gcr.io` is deprecated and will be shut down https://cloud.google.com/artifact-registry/docs/transition/prepare-gcr-shutdown.
Note that you probably want to switch to the controller runtime built in [filters.WithAuthenticationAndAuthorization](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/metrics/filters#WithAuthenticationAndAuthorization) at some point. We'll let you know if we have an example ready.
> Replace `gcr.io` `kube-rbac-proxy` image

- pkg/comp-functions/functions/vshnkeycloak/deploy.go
- pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
- pkg/comp-functions/functions/vshnminio/minio_deploy.go
- pkg/comp-functions/functions/vshnnextcloud/deploy.go
* We have to make sure we can configure registries and repositories for our helm charts in the component. We might want to change the default docker hub registry.
> Set image registry and repository

- apis/exoscale/v1/dbaas_exoscale_kafka.go
- crds/exoscale.appcat.vshn.io_exoscalekafkas.yaml
* Version 3.4 is not available anymore and therefore won't work. This PR will set the version to 3.8 which is the currently supported version
> Add support for Kafka 3.8

- pkg/comp-functions/functions/vshnpostgres/user_management.go
- pkg/comp-functions/functions/vshnpostgres/user_management_test.go
- test/functions/vshn-postgres/usermanagement/02-tls-disabled.yaml
We need to pass the correct ssl mode to the provider-config for provider-sql in order to be able to connect to the postgresql server depending on the ssl mode of the server itself.
> Set SSLMode for provider-sqls provider-config

- README.md
* Adds a small note in section "Getting started with devcontainers" that should help avoid some pitfalls we've encountered whilst building the devcontainer.
> Add note on devcontainer building

- pkg/comp-functions/functions/vshnpostgres/loadBalancer.go
* `role=master` label is never set. We need it to point to `primary` 
* probably Stackgres changed that while ago and we didn't realize
> fixing label selector for our loadbalancer services in vshnpostgresql

- pkg/controller/webhooks/postgresql.go
- pkg/controller/webhooks/postgresql_test.go
* When services has explicitly set instances to 1 then allow major upgrade
> Fix postgres webhook to allow major upgrade when non HA

- pkg/comp-functions/functions/vshnpostgres/connection_details.go
- pkg/comp-functions/functions/vshnpostgres/connection_details_test.go
- pkg/comp-functions/functions/vshnpostgres/user_management.go
- test/functions/vshn-postgres/secrets/02_input_function-io.yaml
The PostgreSQL URL generator relied on the `connectionDetails` of the `Cluster` object. Since we removed that due to the deprovisioning bug, the URL was not generated correctly anymore.
> Re-add password for URL generation

- pkg/comp-functions/functions/common/ingress.go
- pkg/comp-functions/functions/common/ingress_test.go
- pkg/comp-functions/functions/common/util.go
- pkg/comp-functions/functions/vshnforgejo/deploy.go
- pkg/comp-functions/functions/vshnkeycloak/ingress.go
- pkg/comp-functions/functions/vshnkeycloak/ingress_test.go
- pkg/comp-functions/functions/vshnnextcloud/collabora.go
- pkg/comp-functions/functions/vshnnextcloud/collabora_test.go
- pkg/comp-functions/functions/vshnnextcloud/ingress.go
- test/functions/common/02_ingress.yaml
- test/functions/vshnkeycloak/03_withFQDNAndAppsDomain.yaml
* Generalize ingress creation logic
* Create separate ingresses that bundle FQDNs in the following way:
* FQDN is part of an OCP clusters default apps domain and only has one subdomain (`sub1.apps...`)
* FQDN is either _not_ part of said domain or has 2 or more subdomains (`sub2.sub1.apps...`)
* Bundled ingresses will have "letsencrypt" or "wildcard" added to their name according to their TLS config
* Services that only have one FQDN will only create a single ingress with no extra name according to those rules
* Use wildcard certs for the ingress bundling eligible FQDNs (empty TLS config)
Given an apps domain `example.com`:
```bash
❯ k get ing -o custom-columns="NAME:.metadata.name,HOSTS:.spec.rules[*].host"
NAME                               HOSTS
nextcloud-collabora-code-ingress …
```
> Generalize Ingress creation, use wildcard cert with OCP apps domain

- pkg/comp-functions/runtime/function_mgr.go
Even thought the field in a connectionDetail map might already be populated, it might happen that it still contains an empty value.
This commit adds an additional check to the waiting logic to also make sure that the value is not empty.
This will fix a racecondition where a pod can start with an empty value on the very first provisioning.
> Also check for non empty value when waiting for connection details

- .devcontainer/postCreateCommand.sh
- Makefile
- pkg/controller/webhooks/deletionprotection.go
The controller used the control-plane client to check for the existance of the instance namespace. However the instance namespaces only reside on the service clusters.
This lead to an issue that PVCs and other unmanaged objects weren't actually protected in a non-converged setup.
This PR also contains some minor devcontainer optimizations in a separate commit.
> Fix a bug where unmanaged objects aren't protected

- pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
The cluster object references the certificates as connection details. To make sure the deprovisioning works, we now deploy additional usages that ensure the certs will be removed after the cluster object.
This can sometimes lead to raceconditions during the de-provisioning as `provider-kubernetes` will not reconcile the object anymore if the referenced object doesn't exist anymore.
See upstream bug: https://github.com/crossplane-contrib/provider-kubernetes/issues/345
> Protect the certificate by the cluster

- apis/vshn/v1/dbaas_vshn_forgejo.go
- pkg/comp-functions/functions/vshnforgejo/deploy.go
- pkg/comp-functions/functions/vshnnextcloud/ingress.go
If a Forgejo or Nextcloud service is created without having its service name in the name, then the helm chart will add `forgejo/nextcloud` to the service name.  
For example, a `VSHNForgejo` with name `my-forgejo-instance` will create this service: `my-forgejo-instance-pcdj9-http`.  
On the other hand, one with the name `my-cool-instance` creates this service: `my-cool-instance-cgrjz-forgejo-http`.
Same with Nextcloud.
The ingress creation logic currently does not account for that.
This PR fixes this issue for:
- Forgejo & Codey
- Nextcloud
> Fix ingress using wrong service names

- pkg/comp-functions/functions/common/tls.go
- pkg/comp-functions/functions/common/tls_test.go
- pkg/sliexporter/probes/postgresql_test.go
This fixes a nilpointer introduced by the refactored certificate handling.
> Fix nilpointer

- cmd/maintenance.go
- pkg/comp-functions/functions/common/maintenance/maintenance.go
- pkg/comp-functions/functions/common/maintenance/maintenance_test.go
- pkg/comp-functions/functions/vshnmariadb/maintenance.go
- pkg/comp-functions/functions/vshnminio/maintenance.go
- pkg/comp-functions/functions/vshnpostgres/maintenance.go
- pkg/comp-functions/functions/vshnredis/maintenance.go
- pkg/maintenance/forgejo.go
- pkg/maintenance/helm/helmpatcher.go
- pkg/maintenance/keycloak.go
- pkg/maintenance/mariadb.go
- pkg/maintenance/minio.go
- pkg/maintenance/nextcloud.go
- pkg/maintenance/postgresql.go
- pkg/maintenance/redis.go
- pkg/maintenance/redis_test.go
- pkg/maintenance/release/release.go
- pkg/maintenance/release/release_test.go
- pkg/scheme.go
- test/functions/vshn-postgres/deploy/01_default.yaml
- test/functions/vshn-postgres/maintenance/01-GivenSchedule.yaml
- test/functions/vshn-postgres/maintenance/02-GivenNoSchedule.yaml
* Add release management in the maintenance of each service instance for our CI/CD pipeline.
We already assume that the composition revisions have _metadata.appcat.vshn.io/revision_ label set. Going through all service type composition revision, pick revisoins with the highest revision number and get the above revision label to pass it to the claim's _compositionRevisionSelector_.
> Add appcat release management in maintenance

- pkg/comp-functions/functions/vshnforgejo/script/backup.sh
* `forgejo dump` exits if `/data/git/repositories` is missing, causing backup failure.
Now, before a backup starts, this directory will be created if it's missing, ensuring that the backup doesn't fail.
> Forgejo: Fix backup

- pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
- pkg/comp-functions/functions/vshnpostgres/restart.go
- pkg/comp-functions/runtime/function_mgr.go
- test/functions/vshn-postgres/restart/03-KeepRecentReboots.yaml
This change will make Crossplane react much quicker to changes in PostgreSQL that will trigger a restart.
The reason this will take long if the poll interval for Crossplane is set to a high value is because of the asnc restart method we employ.
If a restart is needed for PostgreSQL then Stackgres will set a`PendingRestart` condition to true on the sgcluster object. With the default poll rate of 1 minute it will then take about 1 minute for the restart to actually trigger.
With a poll rate of 1h it would then take 1 hour for the restart to trigger, because Crossplane will then only poll the latest state of the sgcluster object every 60 minutes.
The default poll rate does not apply to Managed Resources that are not marked as ready. Then it will reconcile much quicker.
So if there's a change …
> Improve responsiveness with high poll interval

- pkg/sliexporter/vshnmariadb_controller/vshnmariadb_controller.go
- pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller.go
* Enable HA in MariaDB SLI Exporter. It was set to always false.
> Enable HA for MariaDB in SLI exporter

- pkg/comp-functions/functions/vshnforgejo/deploy.go
* The helm chart might create the `gitea_admin` account first with the same email account as `forgejo_admin` then the pod fails during setup.
> Add default forgejo admin email

- apis/v1/objectstorage_types.go
- crds/appcat.vshn.io_objectbuckets.yaml
- crds/appcat.vshn.io_xobjectbuckets.yaml
- pkg/comp-functions/functions/buckets/exoscalebucket/exoscalebucket.go
- pkg/comp-functions/functions/common/backup/backup.go
- pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
With this change it's now possible to select the default region/zone for the backups.
This enables us to deliver true off-site backups, so in case of a whole datacenter not being available anymore it's possible to restore.
This PR also fixes an annoying issue with Exoscale IAM name clashes. It was previously not possible to provision the buckets for nested services where both of them need a bucket (currently only Nextcloud). Also due to our billing re-creating the same instance in the same claim-namespace also failed.
> Switch backups to use the default region

- pkg/comp-functions/functions/vshnforgejo/deploy.go
This connection detail is specified in the XRD but wasn't set until now.
It's mainly used for cluster internal connections as well as the e2e tests.
> Add Forgejo host connection detail

- apis/vshn/v1/dbaas_vshn_postgresql.go
- crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
- crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
- crds/vshn.appcat.vshn.io_vshnpostgresqls.yaml
- crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
- crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
- crds/vshn.appcat.vshn.io_xvshnpostgresqls.yaml
- pkg/comp-functions/functions/vshnpostgres/register.go
- pkg/controller/webhooks/postgresql.go
- pkg/controller/webhooks/postgresql_test.go
* We need to disable MajorVersion Upgrade feature, as it's not yet production ready
> disabling majorVersionUpgrades

- pkg/comp-functions/functions/common/postgresql.go
- pkg/comp-functions/functions/vshnnextcloud/deploy.go
We discovered that the disk for the embedded PostgreSQL will be set to the same size as the Nextcloud disk.
This PR improves the default configuration and reconciliation behavior for Nextcloud's PostgreSQL dependency.
* Default disk size for the PostgreSQL dependency is set to `10GiB` if not specified by the user.  
* Existing instances will not be downsized if they already use more than `10GiB`.  
* If the current disk size is below `10GiB` and no user-defined value is set, it will be updated to the new default.  
* Adds and enforces `max_connections: "1000"` in PostgreSQL settings.  
* Adds and enforces `max_client_conn: "1000"` in pgBouncer settings.  
* These settings will be reconciled on existing instances unless explicitly overridden by the user.
`bug`, `enhancement`, …
> Fix Nextcloud default PG settings

- cmd/hotfixreleaser.go
- cmd/maintenance.go
- main.go
- pkg/comp-functions/functions/common/maintenance/maintenance.go
- pkg/maintenance/release/release.go
- pkg/maintenance/release/release_test.go
This commit adds a new cmd for AppCat which will discover all composites on a given cluster.
It will then loop over them and switch over to the latest composition revision using the logic already engineered for the maintenance.
> Add hotfix release job

- apis/vshn/v1/dbaas_vshn_redis.go
- crds/vshn.appcat.vshn.io_vshnredis.yaml
- crds/vshn.appcat.vshn.io_xvshnredis.yaml
- pkg/comp-functions/functions/vshnkeycloak/deploy.go
- pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
- pkg/comp-functions/functions/vshnminio/minio_deploy.go
- With the latest version of the keycloak chart, the port definition isn't necessary anymore, as it's already in the chart and will generate a duplicate error while applying.
- The latest Redis chart seems to work fine with older versions as well, so we will allow a broader selection of open source Redis versions
> Helm Chart updates May 2025

- pkg/comp-functions/functions/vshnkeycloak/deploy.go
* For reasons I don't remember, we disabled Keycloak metrics, now they're required, so this change is reenabling monitors in helm values
> reenabling Keycloak service monitors

- config/apiserver/role.yaml
- pkg/apiserver/appcat/appcat.go
- pkg/apiserver/vshn/mariadb/get.go
- pkg/apiserver/vshn/mariadb/list.go
- pkg/apiserver/vshn/nextcloud/get.go
- pkg/apiserver/vshn/nextcloud/list.go
- pkg/apiserver/vshn/postgres/get.go
- pkg/apiserver/vshn/postgres/list.go
- pkg/apiserver/vshn/redis/get.go
- pkg/apiserver/vshn/redis/list.go
* The APIServer needs additional permissions to get the kubeconfig on
a non-converged setup. It needs to read providerconfigs.kubernetes as
well as secrets.
> Add missing roles for APIServer

- pkg/comp-functions/functions/common/mailgun_alerting.go
* This PR fixes a bug we introduced by referencing the correct secret for the mailgun credentials.
> Fix wrong mailgun secret ref for patching secret

- pkg/comp-functions/runtime/function_mgr.go
Crossplane will soon make the realtime mode the default. See https://github.com/crossplane/crossplane/issues/6453
The way we serializse the `Object`s leaves a `creationDate: null` in the inner manifests.
However, this will cause a reconcile loop when the realtime mode is enabled. While not apparante there might also be a reduction in reconciles with Crossplane in poll mode.
In either case, the values that get removed by this commit are garbage and can cause issues down the line.
> Make AppCat realtime compatible

- cmd/hotfixreleaser.go
- cmd/maintenance.go
- pkg/comp-functions/functions/common/maintenance/maintenance.go
- pkg/maintenance/release/release.go
- pkg/maintenance/release/release_test.go
* Minor changes to enable release management
* Added the ability to disable the whole release management and reset all instances
* Can will either happen during maintenance or via hotfix job 
> Enable Function Revisions

- .github/workflows/pr.yml
In order for the function version generation script to work as expected the whole git history has to be available.
By default the checkout action will only shallow fetch the repo. This change ensures that we always have the full history.
> Ensure to fetch whole git history

- pkg/comp-functions/functions/vshnforgejo/deploy.go
- pkg/comp-functions/functions/vshnforgejo/deploy_test.go
- pkg/controller/webhooks/codey.go
- pkg/controller/webhooks/forgejo.go
- test/functions/vshnforgejo/01_default.yaml
* Forgejo and Codey instances will now use compute resources according to their selected plans (CPU, Memory limits and PVC size).  
* Fix a bug in the webhooks Codey FQDN check logic where the (temporary) ACME solver ingress was triggering false positives.
* The ACME solver ingress uses the same hostname as the wildcard/let's encrypt ingress.
> Forgejo/Codey: Set compute resources according to plans

- apis/stackgres/v1/sgcluster.gen.go
- pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
As of StackGres 1.16.0 it's possible to disable Envoy.
It sits in the direct data path of PostgreSQL so the performance of the database is impacted by Envoy. However the only benefit that it brings is some additional connection metrics, which are not worth the additional resource usage and the performance impact.
> Permanently disable Envoy

- .github/workflows/pr.yml
When a new PR is opened in this repo, an equivalent PR in `component-appcat` cannot be created as the action `open-pr-component` fails:  
The checkout action is not fetching tags, which makes the `hack/getversions.sh` script [fail](https://github.com/vshn/appcat/actions/runs/15391133221/job/43364259083#step:5:93) as `git rev-list --tags` returns nothing.
This is basically the same as https://github.com/vshn/appcat/pull/367
> Fix 'open-pr-component' action

- pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
- pkg/comp-functions/functions/vshnpostgres/postgresql_deploy_test.go
- test/functions/vshn-postgres/deploy/03_with_restore.yaml
* The current PITR configuration can't work as we reference the wrong parameter in the `SgCluster`object.
This PR fixes that issue.
> Fix wrong pitr configuration

- cmd/hotfixreleaser.go
- pkg/maintenance/release/release.go
Previously the version update logic for each instances was changed to check for an empty namespace and decide that way if it has to patch the claim or the composite. This was an "improvement" over the previous try'n error approach, as it made things more explicit.
However, provider-kubernetes is currently not able to remove existing fields without switching to server-side-apply:
https://github.com/crossplane-contrib/provider-kubernetes/issues/242#issuecomment-2577579544
So this reverts the logic back to first try for a claim and the fall back to the composite.
> Revert back to try'n error approach for maintenance

- pkg/comp-functions/functions/vshnkeycloak/deploy.go
* enabling metrics for Keycloak
* adding ServiceMonitor that supports self signed certificates and scraping over https (this is necessary, as helm chart doesn't support such scenario)
Component PR: https://github.com/vshn/component-appcat/pull/777
> Keycloak metrics. Appcat's Own ServiceMonitor.

- pkg/comp-functions/runtime/function_mgr.go
* Fixes a bug when copying resources like Secrets or ConfigMaps that have ownerReferences set (e.g., those managed by Vault).
Previously, CopyKubeResource did not clear ownerReferences, which prevented the resource from being synced into the instance namespace.
Component PR: https://github.com/vshn/component-appcat/pull/787
> Hotfix clear ownerReferences when copying kube-objects

- apis/vshn/v1/dbaas_vshn_forgejo.go
- apis/vshn/v1/vshn_nextcloud.go
- crds/vshn.appcat.vshn.io_vshnforgejoes.yaml
- crds/vshn.appcat.vshn.io_vshnnextclouds.yaml
- crds/vshn.appcat.vshn.io_xvshnforgejoes.yaml
- crds/vshn.appcat.vshn.io_xvshnnextclouds.yaml
- test/functions/vshnforgejo/01_default.yaml
* Updated charts: Redis, MariaDB, Nextcloud, Forgejo
* New default versions for  Nextcloud and Forgejo
* Updated Crossplane to v1.20.0 and adedd flags `--enable-realtime-compositions=false` and `--registry=xpkg.upbound.io` to [preserve](https://github.com/crossplane/crossplane/releases/tag/v1.20.0) the previous behavior 
Component PR: https://github.com/vshn/component-appcat/pull/784
Component PR:
> Helm Chart updates June 2025

- pkg/comp-functions/functions/vshnkeycloak/deploy.go
- pkg/comp-functions/functions/vshnkeycloak/deploy_test.go
Fixes a bug where the Keycloaks helm chart values are rendered out as `extraInitContainers: null` if `customFiles` has no length.  
The release fails to install in such a case because the STS template renders out invalid YAML.
Component PR: https://github.com/vshn/component-appcat/pull/802
> VSHNKeycloak: Fix bug with custom files

- pkg/comp-functions/functions/vshnkeycloak/deploy.go
This was re-introduced by https://github.com/vshn/appcat/pull/379/files#diff-9d57e64a014aff26a646229e449affc4afe8e96fc5238920a77758f105cddc14R577 and should be removed, as the configurations are now applied via a job and the Keycloak API, so no new mounts are necessary.
Component PR: https://github.com/vshn/component-appcat/pull/814
> Remove obsolete volumeMount

- pkg/comp-functions/functions/common/maintenance/maintenance.go
- pkg/comp-functions/functions/vshnkeycloak/deploy.go
* After fixing https://github.com/vshn/appcat/pull/414 the Job can't be removed
* When testing before rolling out we didn't run into this
* Added `runtime.KubeOptionAllowDeletion` so the Job can be removed again
Component PR: https://github.com/vshn/component-appcat/pull/827
> Allow deletion of the Keycloak config apply job

- apis/vshn/v1/dbaas_vshn_keycloak.go
- apis/vshn/v1/zz_generated.deepcopy.go
- crds/vshn.appcat.vshn.io_vshnkeycloaks.yaml
- crds/vshn.appcat.vshn.io_xvshnkeycloaks.yaml
- pkg/comp-functions/functions/vshnkeycloak/deploy.go
- pkg/comp-functions/functions/vshnkeycloak/deploy_test.go
- pkg/controller/webhooks/keycloak.go
- test/functions/vshnkeycloak/01_default.yaml
* PR https://github.com/vshn/appcat/pull/394 introduced a change in behaviour when the Config Apply Job should run
* This change corrects the logic so that if a user defines  customConfigurationRef  and/or customEnvVariablesRef during the initial installation, the Config Apply Job will execute accordingly. 
Component PR: https://github.com/vshn/component-appcat/pull/834
> Ensure Keycloak Config Apply Job Executes on Initial Install

- pkg/comp-functions/functions/vshnforgejo/maintenance.go
- pkg/comp-functions/functions/vshnkeycloak/maintenance.go
- pkg/comp-functions/functions/vshnmariadb/maintenance.go
- pkg/comp-functions/functions/vshnmariadb/proxysql.go
- pkg/comp-functions/functions/vshnmariadb/user_management.go
- pkg/comp-functions/functions/vshnmariadb/user_management_test.go
- pkg/comp-functions/functions/vshnminio/maintenance.go
- pkg/comp-functions/functions/vshnnextcloud/maintenance.go
- pkg/comp-functions/functions/vshnpostgres/user_management.go
- pkg/comp-functions/functions/vshnpostgres/user_management_test.go
- pkg/comp-functions/functions/vshnredis/maintenance.go
- pkg/comp-functions/runtime/function_mgr.go
The desiredComposite is not always initialized and can sometimes be empty. So any logic that relies on it to get the state of the observed composite might actually work on wrong values.
This commit fixes this issue.
Component PR: https://github.com/vshn/component-appcat/pull/841
> Fix race conditions due to desiredComposite

- pkg/comp-functions/functions/common/instance_namespace.go
- pkg/comp-functions/functions/vshnnextcloud/collabora.go
- pkg/comp-functions/runtime/function_mgr.go
- test/functions/common/billing.yaml
* Provider-kubernetes uses a filter that only reacts to changes in `.spec` and `.metadata`. As seen [here](https://github.com/crossplane-contrib/provider-kubernetes/blob/main/internal/controller/object/object.go#L196) and [here](https://github.com/crossplane/crossplane-runtime/blob/main/pkg/resource/predicates.go#L51). Unfortunately this disables the polling from Crossplane itself. Which means that the state of observed `Objects` can potentially lag behind by 10 minutes. This lead to many issues with observing `Objects`. For instance that it can take up to 20 minutes for a Keycloak instance to get ready depending on it's configurations in the claim.
* To combat this behavior, we now update a special annotation on each function reconcile, which in turn forces provider-kubernetes to …
> Fixing some race conditions and e2e

- pkg/comp-functions/functions/common/maintenance/maintenance.go
- pkg/comp-functions/functions/vshnkeycloak/deploy.go
- pkg/comp-functions/functions/vshnmariadb/mariadb_deploy.go
- pkg/comp-functions/functions/vshnpostgres/postgresql_deploy.go
- pkg/comp-functions/functions/vshnredis/pvcresize.go
- pkg/comp-functions/functions/vshnredis/redis_deploy.go
- pkg/comp-functions/functions/vshnredis/restore.go
- pkg/maintenance/forgejo.go
- pkg/maintenance/keycloak.go
- pkg/maintenance/mariadb.go
- pkg/maintenance/minio.go
- pkg/maintenance/nextcloud.go
- pkg/maintenance/redis.go
- pkg/maintenance/redis_test.go
- pkg/maintenance/url.go
* In response to the following announcement https://github.com/bitnami/containers/issues/83267 we have to switch to the legacy registry before August 28th, to prevent image pull errors.
Component PR: https://github.com/vshn/component-appcat/pull/851
> Switch Bitnami images to legacy registry

- pkg/comp-functions/functions/vshnredis/backup.go
- pkg/comp-functions/functions/vshnredis/pvcresize.go
- pkg/comp-functions/functions/vshnredis/pvcresize_test.go
- pkg/comp-functions/functions/vshnredis/restore.go
- pkg/comp-functions/functions/vshnredis/script/cleanupRestore.sh
- pkg/comp-functions/functions/vshnredis/script/prepRestore.sh
- pkg/comp-functions/functions/vshnredis/script/recreate.sh
- pkg/comp-functions/functions/vshnredis/script/restore.sh
- test/functions/vshnredis/pvcresize/01_default.yaml
- test/functions/vshnredis/pvcresize/01_job.yaml
- test/functions/vshnredis/restore/01-GivenNoRestoreConfig.yaml
- test/functions/vshnredis/restore/01-GivenRestoreConfig.yaml
- test/functions/vshnredis/restore/01-GivenRestoreConfigNoBN.yaml
- test/functions/vshnredis/restore/01-GivenRestoreConfigNoCN.yaml
* This fixes the restore and resize procedures by updating script references to the new naming convention. Previously, scripts pointed to the old names and failed.
Component PR: https://github.com/vshn/component-appcat/pull/858
> Fix Redis restore and pvc resize

- pkg/comp-functions/functions/vshnpostgres/user_management.go
- pkg/comp-functions/functions/vshnpostgres/user_management_test.go
This commit fixes a bug in the usermanagement feature when the username is different from the dbname.
The bug resulted in a wrong owner of the database.
Component PR: https://github.com/vshn/component-appcat/pull/868
> Fix bug in UserManagement if username != dbname

- pkg/controller/webhooks/keycloak.go
- pkg/controller/webhooks/keycloak_test.go
- pkg/controller/webhooks/nextcloud.go
- pkg/controller/webhooks/nextcloud_test.go
- pkg/controller/webhooks/postgresql.go
- pkg/controller/webhooks/postgresql_test.go
- Implemented controller functionality to ensure the pg encryption can't be changed after an instance has been created
Component PR: https://github.com/vshn/component-appcat/pull/876
> Validate VSHNPG encryption state

- apis/vshn/v1/common_types.go
- apis/vshn/v1/dbaas_vshn_postgresql.go
Fixes an issue where boolean fields with omitempty and default=true could not be set to false via YAML. The YAML serializer would omit false values due to the omitempty tag, causing them to be interpreted as the default true value instead.
Component PR: https://github.com/vshn/component-appcat/pull/879
> Removed omitempty from default=true boolean fields

- pkg/comp-functions/functions/vshnnextcloud/deploy.go
- Fixed a bug where Nextcloud startup times would be slow with a bunch of files in the PVC. See https://docs.appuio.cloud/user/how-to/long-pod-startup.html for more information on the bug.
Component PR: https://github.com/vshn/component-appcat/pull/888
> Fixed long startup times on nextcloud via security contexts

- pkg/comp-functions/functions/common/schedule.go
- pkg/comp-functions/functions/common/schedule_test.go
- pkg/comp-functions/functions/vshnpostgres/schedule_test.go
* We should not configure maintenance and backup only on Tuesday to Wednesday. For security reasons we should expand further the window
** from Sunday (starting 21:00) to Friday
** Window 21:00 - 05:00
Component PR: https://github.com/vshn/component-appcat/pull/877
> Expand maintenance window

- pkg/comp-functions/functions/common/password.go
- pkg/comp-functions/functions/vshnmariadb/user_management.go
- pkg/comp-functions/functions/vshnpostgres/user_management.go
- pkg/comp-functions/runtime/function_mgr.go
- MariaDB did not actually set a password at all
- Made the detection for the password secret more robust. It will now only regenerate if the `Object` itself doesn't exist.
- Provider-SQL requires a `writeConnectionSecretToRef` or password changes won't actually get applied.
Number 2 and 3 contributed to the problems where the password didn't actually match what got applied by provider-sql. I observed edge-cases where mutliple passwords got re-created during privsioning in such a way that provider-sql saw one password but the end user secret got another.
Due to the missing `writeConnectionSecretToRef` the provider never fixed drifted passwords by itself.
However, with the more robust detection there should not be any password re-creation in the first place.
Component PR: …
> Fix some more bugs with user provisioning

- .github/workflows/merge.yml
- pkg/comp-functions/functions/common/password.go
- pkg/comp-functions/functions/common/password_test.go
Previously the check only checked if the secret as a whole existed. However there was a race condition where not all fields got applied during the first creation. Resulting in missing fields.
This change will now check the secrets field by field. As a side effect this allows us to add new fields to existing secrets as well.
Component PR: https://github.com/vshn/component-appcat/pull/893
> Check generated secrets by fields

- pkg/comp-functions/functions/vshnnextcloud/files/backup.sh
Removed `sudo` commands in the backup script of Nextcloud to fix permission errors on OpenShift and added a condition for non OpenShift environments. This is not needed on OpenShift since the user running the job is also the user who owns `occ`. `runuser` would fail there. 
```sh
ls -lah | grep occ
-rwxr-xr-x.  1 1001810000 1001810000  596 Aug 27 13:30 occ
whoami
1001810000
```
Component PR: https://github.com/vshn/component-appcat/pull/894
> Fixed permission denied error for nextcloud backups

- config/controller/cluster-role.yaml
- pkg/controller/webhooks/default_handler.go
This commit adds RBAC so that the controller service account actually has permissions to check the providerconfigs.
Component PR: https://github.com/vshn/component-appcat/pull/934
> Add RBAC for providerconfig checks

- apis/codey/dbaas_vshn_codey.go
- config/controller/cluster-role.yaml
- pkg/controller/webhooks/codey.go
* The CodeyInstance webhook was failing because CodeyInstance didn't implement the `IsBackupEnabled()` method required by the `common.Composite` interface causing type assertion failures.
* Additionally, the FQDN uniqueness check was updated to handle empty `spec.ResourceRef.Name`  on instance creation by conditionally applying the composite name filter only when it's populated.
Component PR: https://github.com/vshn/component-appcat/pull/941
> Fix codey webhook
